version: '3.3'
services:
  keycloak:
    container_name: keycloak
    hostname: keycloak-srv
    volumes:
      - ./keycloak/imports:/opt/jboss/keycloak/imports
      - ./keycloak/theme:/opt/jboss/keycloak/themes/gutcodes
      - ./keycloak/config:/opt/jboss/keycloak/standalone/configuration
      - ./keycloak/db:/opt/jboss/keycloak/standalone/data
    image: jboss/keycloak:14.0.0
    command:
      - "-b 0.0.0.0"
    environment:
      - KEYCLOAK_IMPORT=/opt/jboss/keycloak/imports/realm-export.json
      - DB_VENDOR=h2
      - PROXY_ADDRESS_FORWARDING=true
      - JDBC_PARAMS=enabledTLSProtocols=TLSv1.2
      - JAVA_OPTS=-server -Xms1024m -Xmx1024m
    ports:
      - "8080:8080"
    networks:
      - gut-codes
  backend:
    container_name: backend
    hostname: backend-srv
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    networks:
      - gut-codes
  nginx-server:
    container_name: nginx-server
    hostname: prod.gut.codes
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NGINX_HOST=prod.gut.codes
      - NGINX_PORT=80
    ports:
      - "80:80"
    networks:
      - gut-codes
    depends_on:
      - keycloak
      - backend
networks:
  gut-codes:
    driver: bridge
